"""user role added

Revision ID: 070a8bc2d632
Revises: 3b702e054016
Create Date: 2026-05-17 21:59:36.836689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070a8bc2d632'
down_revision: Union[str, Sequence[str], None] = '3b702e054016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_role_enum AS ENUM ('admin', 'chat-owner', 'reader')")
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'chat-owner', 'reader', name='user_role_enum'), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.execute("DROP TYPE user_role_enum")
    # ### end Alembic commands ###
