"""analysis table id to string

Revision ID: 2717d22fb62a
Revises: b39ec5764926
Create Date: 2026-05-24 01:47:17.327012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2717d22fb62a'
down_revision: Union[str, Sequence[str], None] = 'b39ec5764926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysiss_workspace_id'), table_name='analyses')
    op.create_index(op.f('ix_analyses_workspace_id'), 'analyses', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_workspace_id'), table_name='analyses')
    op.create_index(op.f('ix_analysiss_workspace_id'), 'analyses', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
