"""qapairs source_scenario_id nullable

Revision ID: 28624eb295d5
Revises: 2de65bd43b5b
Create Date: 2026-05-11 13:43:16.605956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28624eb295d5'
down_revision: Union[str, Sequence[str], None] = '2de65bd43b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qapairs', 'source_scenario_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qapairs', 'source_scenario_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
