"""models updated

Revision ID: 2de65bd43b5b
Revises: 2e7842267d27
Create Date: 2026-05-11 00:34:08.356619

"""
from typing import Sequence, Union

import pgvector
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de65bd43b5b'
down_revision: Union[str, Sequence[str], None] = '2e7842267d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragchunks', sa.Column('chapter_index', sa.Integer(), nullable=False))
    op.add_column('ragchunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('ragchunks', sa.Column('token_count', sa.Integer(), nullable=False))
    op.add_column('ragchunks', sa.Column('page_start', sa.Integer(), nullable=False))
    op.add_column('ragchunks', sa.Column('page_end', sa.Integer(), nullable=False))
    op.add_column('ragchunks', sa.Column('language', sa.String(length=20), nullable=False))
    op.alter_column('ragchunks', 'topics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('ragchunks', 'scenario_relevance',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('ragchunks', 'embedding')
    op.add_column('ragchunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragchunks', 'embedding')
    op.add_column('ragchunks', sa.Column('embedding', postgresql.JSONB(), nullable=True))
    op.alter_column('ragchunks', 'scenario_relevance',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('ragchunks', 'topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('ragchunks', 'language')
    op.drop_column('ragchunks', 'page_end')
    op.drop_column('ragchunks', 'page_start')
    op.drop_column('ragchunks', 'token_count')
    op.drop_column('ragchunks', 'chunk_index')
    op.drop_column('ragchunks', 'chapter_index')
    # ### end Alembic commands ###
