"""Scenarios model updated

Revision ID: 2e7842267d27
Revises: 5185ae2866fe
Create Date: 2026-05-06 18:13:59.490168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e7842267d27'
down_revision: Union[str, Sequence[str], None] = '5185ae2866fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragchunks', sa.Column('source_document_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ragchunks_source_document_id'), 'ragchunks', ['source_document_id'], unique=False)
    op.create_foreign_key(None, 'ragchunks', 'sourcedocuments', ['source_document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('scenarios', 'stakeholders',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenarios', 'time_pressure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('scenarios', 'decision_nodes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenarios', 'relevant_tactics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenarios', 'difficulty_for_rookie',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.alter_column('scenarios', 'difficulty_for_rookie',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scenarios', 'relevant_tactics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenarios', 'decision_nodes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('scenarios', 'time_pressure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scenarios', 'stakeholders',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'ragchunks', type_='foreignkey')
    op.drop_index(op.f('ix_ragchunks_source_document_id'), table_name='ragchunks')
    op.drop_column('ragchunks', 'source_document_id')
    # ### end Alembic commands ###
