"""workspace table altered

Revision ID: 3b702e054016
Revises: e404072fcf24
Create Date: 2026-05-16 00:00:46.200625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b702e054016'
down_revision: Union[str, Sequence[str], None] = 'e404072fcf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('workspaces', sa.Column('description', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('generating_chat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.drop_constraint(op.f('workspaces_owner_id_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workspaces', 'owner_id')
    op.drop_column('workspaces', 'channels')
    op.drop_column('workspaces', 'constraints')
    op.drop_column('workspaces', 'voice_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('voice_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_owner_id_fkey'), 'workspaces', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_column('workspaces', 'generating_chat_id')
    op.drop_column('workspaces', 'description')
    op.drop_column('workspaces', 'user_id')
    # ### end Alembic commands ###
