"""analysis_id_uuid_str

Revision ID: 43ef5d9bbf55
Revises: e2605b9fd40c
Create Date: 2026-05-28 13:16:09.873720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ef5d9bbf55'
down_revision: Union[str, Sequence[str], None] = 'e2605b9fd40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop the foreign key constraint first
    op.drop_constraint("roadmaps_analysis_id_fkey", "roadmaps", type_="foreignkey")

    # 2. Change case_analysis.id to VARCHAR
    op.alter_column(
        "case_analysis", "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(36),
        postgresql_using="id::varchar(36)",
    )

    # 3. Change roadmaps.analysis_id to VARCHAR to match
    op.alter_column(
        "roadmaps", "analysis_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(36),
        postgresql_using="analysis_id::varchar(36)",
    )

    # 4. Recreate the foreign key
    op.create_foreign_key(
        "roadmaps_analysis_id_fkey",
        "roadmaps", "case_analysis",
        ["analysis_id"], ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("roadmaps_analysis_id_fkey", "roadmaps", type_="foreignkey")
    op.alter_column("roadmaps", "analysis_id",
                    existing_type=sa.String(36), type_=sa.INTEGER(),
                    postgresql_using="analysis_id::integer")
    op.alter_column("case_analysis", "id",
                    existing_type=sa.String(36), type_=sa.INTEGER(),
                    postgresql_using="id::integer")
    op.create_foreign_key("roadmaps_analysis_id_fkey", "roadmaps", "case_analysis",
                          ["analysis_id"], ["id"])
    # ### end Alembic commands ###
