"""user role naming and adding chat owner id

Revision ID: 4401de2d6e05
Revises: 4f4f00a81e91
Create Date: 2026-05-20 14:12:29.912525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4401de2d6e05'
down_revision: Union[str, Sequence[str], None] = '4f4f00a81e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute(
        "ALTER TYPE user_role_enum RENAME VALUE 'chat-owner' TO 'chat_owner'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_column('chats', 'user_id')
    op.execute(
        "ALTER TYPE user_role_enum RENAME VALUE 'chat_owner' TO 'chat-owner'"
    )
    # ### end Alembic commands ###
