"""adding source doc model and adjusting scenario table

Revision ID: 46df6440a31d
Revises: bd2f3a90c850
Create Date: 2026-04-26 16:57:08.268060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46df6440a31d'
down_revision: Union[str, Sequence[str], None] = 'bd2f3a90c850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcedocuments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sourcedocuments_id'), 'sourcedocuments', ['id'], unique=False)
    op.create_index(op.f('ix_sourcedocuments_source_slug'), 'sourcedocuments', ['source_slug'], unique=True)
    op.add_column('scenarios', sa.Column('source_slug', sa.String(length=160), nullable=False))
    op.add_column('scenarios', sa.Column('source_chunk_id', sa.String(length=240), nullable=False))
    op.add_column('scenarios', sa.Column('chapter_title', sa.String(length=500), nullable=True))
    op.add_column('scenarios', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_scenarios_source_chunk_id'), 'scenarios', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_scenarios_source_slug'), 'scenarios', ['source_slug'], unique=False)
    op.drop_column('scenarios', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_scenarios_source_slug'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_source_chunk_id'), table_name='scenarios')
    op.drop_column('scenarios', 'raw')
    op.drop_column('scenarios', 'chapter_title')
    op.drop_column('scenarios', 'source_chunk_id')
    op.drop_column('scenarios', 'source_slug')
    op.drop_index(op.f('ix_sourcedocuments_source_slug'), table_name='sourcedocuments')
    op.drop_index(op.f('ix_sourcedocuments_id'), table_name='sourcedocuments')
    op.drop_table('sourcedocuments')
    # ### end Alembic commands ###
