"""roamdaps table imported to env

Revision ID: 4ef57809789e
Revises: 50fc2196dc47
Create Date: 2026-03-01 19:53:34.410257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4ef57809789e'
down_revision: Union[str, Sequence[str], None] = '50fc2196dc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# define enums to avoid collisions
roadmap_base_phases = postgresql.ENUM(
    'T0_30M',
    'T30M_2H', 'H2_24H',
    'D1_7', 'MONITORING',
    name='phase_enum',
    create_type=False,
)

roadmap_item_type = postgresql.ENUM(
    'STRATEGY',
    'TACTIC',
    'MESSAGE',
    'MONITORING',
    name='item_type_enum',
    create_type=False,
)

roadmap_priority = postgresql.ENUM(
    'P0',
    'P1',
    'P2',
    name='priority_enum',
    create_type=False,
)

roadmap_status = postgresql.ENUM(
    'TODO',
    'DOING',
    'DONE',
    'BLOCKED',
    name='status_enum',
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # create if missing
    roadmap_base_phases.create(bind, checkfirst=True)
    roadmap_item_type.create(bind, checkfirst=True)
    roadmap_priority.create(bind, checkfirst=True)
    roadmap_status.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),

    # use the enum objects (won't try to CREATE TYPE again)
    sa.Column('phase', roadmap_base_phases, nullable=False),

    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),

    # use the enum objects (won't try to CREATE TYPE again)
    sa.Column('item_type', roadmap_item_type, nullable=False),
    sa.Column('priority', roadmap_priority, nullable=False),
    sa.Column('status', roadmap_status, nullable=False),

    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('ai_rationale', sa.String(), nullable=True),
    sa.Column('risk_if_skipped', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
    roadmap_base_phases.drop(bind, checkfirst=True)
    roadmap_item_type.drop(bind, checkfirst=True)
    roadmap_priority.drop(bind, checkfirst=True)
    roadmap_status.drop(bind, checkfirst=True)
