"""fix_roadmap_fk_to_analyses

Revision ID: 4f557bbb5b9e
Revises: 43ef5d9bbf55
Create Date: 2026-05-28 13:34:46.725942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f557bbb5b9e'
down_revision: Union[str, Sequence[str], None] = '43ef5d9bbf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('roadmaps_analysis_id_fkey'), 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'analyses', ['analysis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key(op.f('roadmaps_analysis_id_fkey'), 'roadmaps', 'case_analysis', ['analysis_id'], ['id'])
    # ### end Alembic commands ###
