"""adding training sample table, added stringllify of the decision node

Revision ID: 5185ae2866fe
Revises: b0041d2fb27d
Create Date: 2026-04-26 20:00:15.110199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5185ae2866fe'
down_revision: Union[str, Sequence[str], None] = 'b0041d2fb27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingsamples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_qa_id', sa.Integer(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_qa_id'], ['qapairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainingsamples_id'), 'trainingsamples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainingsamples_id'), table_name='trainingsamples')
    op.drop_table('trainingsamples')
    # ### end Alembic commands ###
