"""updating workspace table

Revision ID: 5747beb6fb01
Revises: f407efa1f5b6
Create Date: 2026-05-21 03:58:51.919009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5747beb6fb01'
down_revision: Union[str, Sequence[str], None] = 'f407efa1f5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('language', sa.String(length=2), nullable=False))
    op.add_column('workspaces', sa.Column('do_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workspaces', sa.Column('dont_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workspaces', sa.Column('preferred_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workspaces', sa.Column('forbidden_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workspaces', sa.Column('example_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workspaces', sa.Column('tov_formality', sa.Integer(), nullable=False))
    op.add_column('workspaces', sa.Column('tov_empathy', sa.Integer(), nullable=False))
    op.add_column('workspaces', sa.Column('tov_assertiveness', sa.Integer(), nullable=False))
    op.add_column('workspaces', sa.Column('tov_transparency', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'tov_transparency')
    op.drop_column('workspaces', 'tov_assertiveness')
    op.drop_column('workspaces', 'tov_empathy')
    op.drop_column('workspaces', 'tov_formality')
    op.drop_column('workspaces', 'example_messages')
    op.drop_column('workspaces', 'forbidden_phrases')
    op.drop_column('workspaces', 'preferred_terms')
    op.drop_column('workspaces', 'dont_rules')
    op.drop_column('workspaces', 'do_rules')
    op.drop_column('workspaces', 'language')
    # ### end Alembic commands ###
