"""fix to the case analysis

Revision ID: 6e06e2fde11f
Revises: 28624eb295d5
Create Date: 2026-05-13 23:13:31.984296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e06e2fde11f'
down_revision: Union[str, Sequence[str], None] = '28624eb295d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_analysis', sa.Column('risk_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_analysis', 'risk_score')
    # ### end Alembic commands ###
