"""roadmaps model updated

Revision ID: 6e1845e4939e
Revises: 8efa53364412
Create Date: 2026-05-15 13:33:48.650897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e1845e4939e'
down_revision: Union[str, Sequence[str], None] = '8efa53364412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('analysis_id', sa.Integer(), nullable=False))
    op.add_column('roadmaps', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('roadmaps', sa.Column('crisis_type', sa.String(), nullable=False))
    op.add_column('roadmaps', sa.Column('confidence', sa.String(), nullable=False))
    op.add_column('roadmaps', sa.Column('roadmap_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_roadmaps_analysis_id'), 'roadmaps', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_workspace_id'), 'roadmaps', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('roadmaps_case_id_fkey'), 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'case_analysis', ['analysis_id'], ['id'])
    op.create_foreign_key(None, 'roadmaps', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('roadmaps', 'ai_rationale')
    op.drop_column('roadmaps', 'priority')
    op.drop_column('roadmaps', 'risk_if_skipped')
    op.drop_column('roadmaps', 'order_index')
    op.drop_column('roadmaps', 'case_id')
    op.drop_column('roadmaps', 'item_type')
    op.drop_column('roadmaps', 'phase')
    op.drop_column('roadmaps', 'description')
    op.drop_column('roadmaps', 'title')
    op.drop_column('roadmaps', 'due_at')
    op.drop_column('roadmaps', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('status', postgresql.ENUM('draft', 'pending', 'analysed', name='status_enum'), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('roadmaps', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('roadmaps', sa.Column('phase', postgresql.ENUM('T0_30M', 'T30M_2H', 'H2_24H', 'D1_7', 'MONITORING', name='phase_enum'), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('item_type', postgresql.ENUM('STRATEGY', 'TACTIC', 'MESSAGE', 'MONITORING', name='item_type_enum'), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('risk_if_skipped', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('roadmaps', sa.Column('priority', postgresql.ENUM('P0', 'P1', 'P2', name='priority_enum'), autoincrement=False, nullable=False))
    op.add_column('roadmaps', sa.Column('ai_rationale', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key(op.f('roadmaps_case_id_fkey'), 'roadmaps', 'cases', ['case_id'], ['id'])
    op.drop_index(op.f('ix_roadmaps_workspace_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_analysis_id'), table_name='roadmaps')
    op.drop_column('roadmaps', 'roadmap_json')
    op.drop_column('roadmaps', 'confidence')
    op.drop_column('roadmaps', 'crisis_type')
    op.drop_column('roadmaps', 'workspace_id')
    op.drop_column('roadmaps', 'analysis_id')
    # ### end Alembic commands ###
