"""case analysis table name alt, adding to the env

Revision ID: 75d359afcbd6
Revises: f9723de6778b
Create Date: 2026-03-01 15:25:19.727011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d359afcbd6'
down_revision: Union[str, Sequence[str], None] = 'f9723de6778b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('crisis_type', sa.Enum('reputational_crisis', 'information_disinformation_crisis', 'operational_failure_crisis', 'values_ethics_crisis', 'leadership_personal_crisis', 'physical_or_cyber_security_crisis', name='communications_crisis_type_enum'), nullable=False),
    sa.Column('stage', sa.Enum('signal_detection', 'trigger_event', 'acute_crisis', 'stabilization', 'recovery', 'post_crisis_learning', name='communications_crisis_stage_enum'), nullable=False),
    sa.Column('attribution', sa.Enum('external_attack', 'external_unintentional', 'internal_unintentional', 'internal_negligence', 'internal_misconduct', 'systemic_failure', 'mixed_attribution', 'unknown', name='communications_crisis_attribution_enum'), nullable=False),
    sa.Column('evidence_confidence', sa.Enum('very_low', 'low', 'medium', 'high', 'very_high', 'confirmed', name='communications_crisis_evidence_confidence_enum'), nullable=False),
    sa.Column('factors_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('retrieved_refs_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_analysis')
    # ### end Alembic commands ###
