"""case analysis table name alt, adding to the env

Revision ID: 75d359afcbd6
Revises: f9723de6778b
Create Date: 2026-03-01 15:25:19.727011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d359afcbd6'
down_revision: Union[str, Sequence[str], None] = 'f9723de6778b'

# define enums to avoid collisions
crisis_type_enum = postgresql.ENUM(
    'reputational_crisis',
    'information_disinformation_crisis',
    'operational_failure_crisis',
    'values_ethics_crisis',
    'leadership_personal_crisis',
    'physical_or_cyber_security_crisis',
    name='communications_crisis_type_enum',
    create_type=False,
)

crisis_stage_enum = postgresql.ENUM(
    'signal_detection',
    'trigger_event',
    'acute_crisis',
    'stabilization',
    'recovery',
    'post_crisis_learning',
    name='communications_crisis_stage_enum',
    create_type=False,
)

crisis_attribution_enum = postgresql.ENUM(
    'external_attack',
    'external_unintentional',
    'internal_unintentional',
    'internal_negligence',
    'internal_misconduct',
    'systemic_failure',
    'mixed_attribution',
    'unknown',
    name='communications_crisis_attribution_enum',
    create_type=False,
)

crisis_evidence_confidence_enum = postgresql.ENUM(
    'very_low',
    'low',
    'medium',
    'high',
    'very_high',
    'confirmed',
    name='communications_crisis_evidence_confidence_enum',
    create_type=False,
)

branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # create types only if missing
    crisis_type_enum.create(bind, checkfirst=True)
    crisis_stage_enum.create(bind, checkfirst=True)
    crisis_attribution_enum.create(bind, checkfirst=True)
    crisis_evidence_confidence_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'case_analysis',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('case_id', sa.Integer(), sa.ForeignKey('cases.id'), nullable=False),
        sa.Column('workspace_id', sa.Integer(), sa.ForeignKey('workspaces.id'), nullable=False),

        # use the enum objects (won't try to CREATE TYPE again)
        sa.Column('crisis_type', crisis_type_enum, nullable=False),
        sa.Column('stage', crisis_stage_enum, nullable=False),
        sa.Column('attribution', crisis_attribution_enum, nullable=False),
        sa.Column('evidence_confidence', crisis_evidence_confidence_enum, nullable=False),

        sa.Column('factors_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('retrieved_refs_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_analysis')
    # ### end Alembic commands ###
    crisis_evidence_confidence_enum.drop(bind, checkfirst=True)
    crisis_attribution_enum.drop(bind, checkfirst=True)
    crisis_stage_enum.drop(bind, checkfirst=True)
    crisis_type_enum.drop(bind, checkfirst=True)
