"""case analytics nullable id

Revision ID: 897b3009dfcb
Revises: 92db8d5c1570
Create Date: 2026-05-14 19:39:13.907671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897b3009dfcb'
down_revision: Union[str, Sequence[str], None] = '92db8d5c1570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_analysis', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('case_analysis', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_analysis', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('case_analysis', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
