"""adding tactics table

Revision ID: 8a75df735740
Revises: 46df6440a31d
Create Date: 2026-04-26 19:17:13.595053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a75df735740'
down_revision: Union[str, Sequence[str], None] = '46df6440a31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('when_to_apply', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('anti_pattern', sa.String(), nullable=True),
    sa.Column('crisis_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_slug', sa.String(length=160), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=240), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactics_id'), 'tactics', ['id'], unique=False)
    op.create_index(op.f('ix_tactics_slug'), 'tactics', ['slug'], unique=False)
    op.create_index(op.f('ix_tactics_source_chunk_id'), 'tactics', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_tactics_source_slug'), 'tactics', ['source_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tactics_source_slug'), table_name='tactics')
    op.drop_index(op.f('ix_tactics_source_chunk_id'), table_name='tactics')
    op.drop_index(op.f('ix_tactics_slug'), table_name='tactics')
    op.drop_index(op.f('ix_tactics_id'), table_name='tactics')
    op.drop_table('tactics')
    # ### end Alembic commands ###
