"""chat share link table naming update

Revision ID: a580087176b8
Revises: c72e82d9f724
Create Date: 2026-05-20 14:26:16.755641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a580087176b8'
down_revision: Union[str, Sequence[str], None] = 'c72e82d9f724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_share_links_chat_id'), 'chat_share_links', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_share_links_token'), 'chat_share_links', ['token'], unique=True)
    op.drop_index(op.f('ix_chatsharelinks_chat_id'), table_name='chatsharelinks')
    op.drop_index(op.f('ix_chatsharelinks_token'), table_name='chatsharelinks')
    op.drop_table('chatsharelinks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsharelinks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chatsharelinks_chat_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('chatsharelinks_created_by_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chatsharelinks_pkey'))
    )
    op.create_index(op.f('ix_chatsharelinks_token'), 'chatsharelinks', ['token'], unique=True)
    op.create_index(op.f('ix_chatsharelinks_chat_id'), 'chatsharelinks', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_chat_share_links_token'), table_name='chat_share_links')
    op.drop_index(op.f('ix_chat_share_links_chat_id'), table_name='chat_share_links')
    op.drop_table('chat_share_links')
    # ### end Alembic commands ###
