"""adding decision node table

Revision ID: b0041d2fb27d
Revises: 8a75df735740
Create Date: 2026-04-26 19:48:02.079257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0041d2fb27d'
down_revision: Union[str, Sequence[str], None] = '8a75df735740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisionnodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=220), nullable=False),
    sa.Column('source_scenario_id', sa.String(length=220), nullable=True),
    sa.Column('situation', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action_id', sa.String(length=80), nullable=True),
    sa.Column('common_rookie_mistake', sa.String(), nullable=True),
    sa.Column('consequence_if_wrong', sa.String(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('source_slug', sa.String(length=160), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=240), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisionnodes_decision_id'), 'decisionnodes', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decisionnodes_id'), 'decisionnodes', ['id'], unique=False)
    op.create_index(op.f('ix_decisionnodes_source_chunk_id'), 'decisionnodes', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_decisionnodes_source_scenario_id'), 'decisionnodes', ['source_scenario_id'], unique=False)
    op.create_index(op.f('ix_decisionnodes_source_slug'), 'decisionnodes', ['source_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisionnodes_source_slug'), table_name='decisionnodes')
    op.drop_index(op.f('ix_decisionnodes_source_scenario_id'), table_name='decisionnodes')
    op.drop_index(op.f('ix_decisionnodes_source_chunk_id'), table_name='decisionnodes')
    op.drop_index(op.f('ix_decisionnodes_id'), table_name='decisionnodes')
    op.drop_index(op.f('ix_decisionnodes_decision_id'), table_name='decisionnodes')
    op.drop_table('decisionnodes')
    # ### end Alembic commands ###
