"""add clarification_count to analyses

Revision ID: e2605b9fd40c
Revises: 2717d22fb62a
Create Date: 2026-05-24 17:12:06.869156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2605b9fd40c'
down_revision: Union[str, Sequence[str], None] = '2717d22fb62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    def upgrade() -> None:
        op.add_column(
            "analyses",
            sa.Column(
                "clarification_count",
                sa.Integer(),
                nullable=False,
                server_default="0",  # ← fills existing rows with 0
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'clarification_count')
    # ### end Alembic commands ###
